### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#104]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub workflow is failing because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` that is not available in the repository secrets. While the other two jobs (`issue-triage-manager` and `guidance-triage-manager`) successfully use the standard `GITHUB_TOKEN` secret, the `pr-triage-manager` job is configured to use a different token that doesn't exist.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Modify the workflow file to use the standard GITHUB_TOKEN secret instead of PROJEN_GITHUB_TOKEN
2. Open the `.github/workflows/issue-label-assign.yml` file
3. Locate the `pr-triage-manager` job section
4. Replace the github-token line with the standard token
5. The corrected code should be:

```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

6. Commit and push the changes to the repository
7. Re-run the workflow to verify the fix
