### ISSUE TITLE
GitHub Action Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#113]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub workflow is failing because it's using a non-existent or invalid GitHub token. The workflow is trying to use `PROJEN_GITHUB_TOKEN` secret for pull request triaging, but this token is either not defined in the repository secrets or doesn't have the required permissions.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-24T00:05:59.0492766Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the non-existent `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's automatically available in GitHub Actions
2. Update the `github-token` parameter in the `pr-triage-manager` job
3. Ensure the token has the required permissions (which are already correctly set in the workflow)

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

This change will use the default GitHub token that's automatically provided to all GitHub Actions workflows, which should have the necessary permissions as defined in the `permissions` section.
