### ISSUE TITLE
GitHub Workflow Failure: Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#116]
## Root Cause Analysis

The "pr-triage-manager" job in the GitHub workflow "Set Issue Label and Assignee" is failing with the error message "Parameter token or opts.auth is required". This indicates that the GitHub token specified in the workflow configuration is not being properly passed to the GitHub API client used by the aws-issue-triage-manager action.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the non-existent `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's automatically provided by GitHub Actions.
2. Update the pr-triage-manager job in the workflow file as follows:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

3. If a custom token with specific permissions is needed, ensure that the `PROJEN_GITHUB_TOKEN` secret is properly configured in the repository settings.
4. Verify that the token has the necessary permissions to access pull request data and assign reviewers.

## Confidence Level
95% - The error message clearly indicates a missing or invalid GitHub token, and the workflow file shows the use of a non-standard token name that likely doesn't exist in the repository secrets.
