### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in issue-label-assign.yml

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#119]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job because it's using a GitHub token named `PROJEN_GITHUB_TOKEN` that is either missing or improperly configured. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the aws-github-ops/aws-issue-triage-manager action is not being provided correctly.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-24T00:08:13.6506458Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the non-existent "PROJEN_GITHUB_TOKEN" with the default "GITHUB_TOKEN" that's automatically provided by GitHub Actions:
   - Open the workflow file at .github/workflows/issue-label-assign.yml
   - Locate the pr-triage-manager job
   - Change the github-token parameter from "${{ secrets.PROJEN_GITHUB_TOKEN }}" to "${{ secrets.GITHUB_TOKEN }}"
   - The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

2. Alternatively, if a custom token with specific permissions is needed:
   - Create a new repository secret named "PROJEN_GITHUB_TOKEN" with appropriate permissions
   - Ensure the token has permissions to read and write to pull requests
