### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#125]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job because it's attempting to use a GitHub token named `PROJEN_GITHUB_TOKEN` which is either not defined in the repository secrets or not properly accessible. The error message "Parameter token or opts.auth is required" indicates that the authentication token was not provided or was invalid when the action tried to interact with the GitHub API.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom PROJEN_GITHUB_TOKEN with the default GITHUB_TOKEN that's automatically provided by GitHub Actions:
   - Open the workflow file at .github/workflows/issue-label-assign.yml
   - Locate the pr-triage-manager job
   - Replace the github-token line with the standard token

2. Update the code to:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

3. If a custom token with elevated permissions is actually required:
   - Add the PROJEN_GITHUB_TOKEN to the repository secrets in the GitHub repository settings
   - Ensure it has the necessary permissions for pull request operations
