### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#126]
## Issue Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing or invalid GitHub token.

## Root Cause Analysis
**Confidence Level:** 95%

The root cause of the workflow failure is in the "pr-triage-manager" job where the GitHub token authentication is failing. The job is using "PROJEN_GITHUB_TOKEN" secret which is either not defined or not properly configured in the repository. The error message "Parameter token or opts.auth is required" clearly indicates that the authentication token is missing or invalid when the aws-issue-triage-manager action attempts to authenticate with GitHub.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
2025-06-24T00:09:21.6539992Z ##[error]Parameter token or opts.auth is required
```

### Option 1: Add the missing secret
1. Add the missing PROJEN_GITHUB_TOKEN secret to the repository's secrets in GitHub:
   - Go to the repository settings
   - Navigate to Secrets and variables > Actions
   - Add a new repository secret named PROJEN_GITHUB_TOKEN with a valid GitHub token value

### Option 2: Use the default GitHub token
1. Modify the workflow file to use the default GITHUB_TOKEN which is automatically provided by GitHub Actions:
   - Open the .github/workflows/issue-label-assign.yml file
   - Replace the github-token line in the pr-triage-manager job with:
   
   ```yaml
   github-token: "${{ secrets.GITHUB_TOKEN }}"
   ```

2. Commit the changes to the workflow file
3. Re-run the workflow to verify the fix works properly

Note: The other jobs in the workflow (`issue-triage-manager` and `guidance-triage-manager`) are using the default `GITHUB_TOKEN` and are working correctly.
