### ISSUE TITLE
GitHub Action Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#13]
## Root Cause Analysis

The GitHub Actions workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job because it's attempting to use a non-existent secret named `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that's available by default in GitHub Actions.

### Error Details

```
##[error]Parameter token or opts.auth is required
```

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's automatically available in GitHub Actions
2. Update the pr-triage-manager job in the workflow file to use the correct token
3. Commit the changes to the repository

### Corrected Code

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Confidence Level
95% - The error message clearly indicates a missing token, and the workflow file shows the use of a non-standard token name.
