### ISSUE TITLE
GitHub Workflow Failure: Incorrect GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#135]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an incorrect GitHub token configuration. The job is attempting to use a non-existent secret called `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that is used successfully in the other jobs.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Solution Plan
1. Modify the pr-triage-manager job in the issue-label-assign.yml workflow file
2. Replace the non-existent PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN
3. Ensure the permissions are properly set (which they already are)
4. Test the workflow after making the change

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
