### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#137]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The workflow failure is caused by an incorrect GitHub token reference in the pr-triage-manager job. The job is using `PROJEN_GITHUB_TOKEN` which is either not defined or not properly configured with the required permissions.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the default `GITHUB_TOKEN` that's automatically provided by GitHub Actions
2. Update the pr-triage-manager job in the issue-label-assign.yml file to use the correct token
3. Ensure the token has the necessary permissions for pull-requests and issues

### Recommended Changes

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
