### ISSUE TITLE
Missing PROJEN_GITHUB_TOKEN in PR triage manager workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#143]
# Root Cause Analysis

## Summary
The pr-triage-manager job in the GitHub workflow is failing because it's attempting to use a GitHub token named PROJEN_GITHUB_TOKEN that is either missing or not properly configured in the repository secrets. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the aws-github-ops/aws-issue-triage-manager action is not being provided correctly.

## Confidence Level
95%

## Impacted File
`.github/workflows/issue-label-assign.yml`

## Problematic Code Snippet
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Error Log
```
2025-06-24T00:18:12.3103634Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan
1. Check if the PROJEN_GITHUB_TOKEN secret exists in the repository settings
2. If the secret doesn't exist, create it with appropriate permissions
3. If you don't have a specific PROJEN_GITHUB_TOKEN, modify the workflow to use the default GITHUB_TOKEN instead
4. Update the pr-triage-manager job in the issue-label-assign.yml file to use the correct token:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
