### ISSUE TITLE
GitHub Workflow Failure: Missing or Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#149]
# Root Cause Analysis: GitHub Workflow Failure

## Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the "pr-triage-manager" job due to a missing or incorrectly configured GitHub token. The error message "Parameter token or opts.auth is required" indicates that the GitHub token was not properly passed to the GitHub API when the aws-issue-triage-manager action attempted to authenticate.

## Confidence Level
95%

## Impacted File
`.github/workflows/issue-label-assign.yml`

## Error Details
```
2025-06-24T00:26:27.3838642Z ##[error]Parameter token or opts.auth is required
```

## Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Root Cause Analysis
The workflow is configured to use "PROJEN_GITHUB_TOKEN" but this token is either not defined in the repository secrets or is incorrectly configured. The GitHub API requires proper authentication to perform operations on pull requests, and without a valid token, the action fails.

## Solution Plan

1. Replace the PROJEN_GITHUB_TOKEN with the default GITHUB_TOKEN that is automatically provided by GitHub Actions:
   - Open the workflow file at .github/workflows/issue-label-assign.yml
   - Locate the pr-triage-manager job
   - Replace the github-token line with: github-token: "${{ secrets.GITHUB_TOKEN }}"

2. Alternatively, if PROJEN_GITHUB_TOKEN is needed for specific permissions:
   - Add the PROJEN_GITHUB_TOKEN to the repository secrets in the GitHub repository settings
   - Ensure it has the necessary permissions for pull request operations

3. Commit the changes to the workflow file
4. Re-run the workflow

## Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
