### ISSUE TITLE
GitHub Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#151]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's using an incorrect GitHub token. The job is configured to use `PROJEN_GITHUB_TOKEN` but this token is either not defined in the repository secrets or is not being passed correctly to the GitHub API, resulting in an authentication error.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Update the pr-triage-manager job to use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

2. Alternatively, if PROJEN_GITHUB_TOKEN is required for specific permissions, ensure it's properly defined in the repository secrets with the necessary scopes.

3. Verify that the aws-issue-triage-manager action has the correct input parameter name for the token. If it's expecting a different parameter name than "github-token", update accordingly.
