### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#152]
## Root Cause Analysis

The GitHub Actions workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job due to a missing GitHub token. The job is configured to use a non-existent token named `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that's successfully used in the other jobs.

### Error Details

```
##[error]Parameter token or opts.auth is required
```

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution

1. Edit the `.github/workflows/issue-label-assign.yml` file
2. Replace the non-existent `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` in the pr-triage-manager job
3. The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

4. Commit and push the changes to trigger the workflow again

## Confidence Level
High (95%) - The error message clearly indicates a missing token, and the other jobs using `GITHUB_TOKEN` are working correctly.
