### ISSUE TITLE
Fix authentication issue in PR triage manager workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#153]
# Root Cause Analysis: GitHub Actions Workflow Failure

## Summary
The workflow `Set Issue Label and Assignee` is failing due to an authentication issue in the `pr-triage-manager` job. The job is attempting to use a GitHub token that is either missing or invalid.

## Confidence Level
95%

### Authentication Error in PR Triage Manager Job

**Analysis:**
The workflow failure is caused by an authentication issue in the pr-triage-manager job. The job is using the "PROJEN_GITHUB_TOKEN" secret which is either missing or invalid, resulting in the error "Parameter token or opts.auth is required" when the aws-issue-triage-manager action attempts to authenticate with GitHub.

**Impacted File:**
`.github/workflows/issue-label-assign.yml`

**Problematic Code:**
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

**Error Log:**
```
2025-06-24T00:25:31.5471951Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the missing or invalid "PROJEN_GITHUB_TOKEN" with the standard "GITHUB_TOKEN" that's automatically provided by GitHub Actions
2. Update the pr-triage-manager job in the issue-label-assign.yml file to use the correct token
3. Ensure the token has the necessary permissions for the action to work with issues and pull requests
4. The corrected code should be:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
