### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#159]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an authentication error. The job is configured to use `PROJEN_GITHUB_TOKEN` which appears to be either undefined or doesn't have the required permissions.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Analysis
The workflow is failing because the "pr-triage-manager" job is using an incorrect GitHub token. The job is configured to use "PROJEN_GITHUB_TOKEN" which is either not defined or doesn't have the required permissions, resulting in an authentication error.

It's worth noting that the other jobs in the same workflow (`issue-triage-manager` and `guidance-triage-manager`) are successfully using the standard `GITHUB_TOKEN` and completing without errors.

### Solution Plan
1. Update the GitHub token in the pr-triage-manager job to use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN
2. Modify the workflow file to use the same token that works in the other jobs
3. Replace the token reference in the pr-triage-manager job as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```
