### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#167]
## Root Cause Analysis

**Confidence Level**: 95%

### Problem Description

The GitHub Actions workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job due to a missing GitHub token. The job is attempting to use `PROJEN_GITHUB_TOKEN` which is either not defined or not accessible in the repository secrets. The error message `Parameter token or opts.auth is required` indicates that the GitHub API call is failing due to missing authentication.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
2025-06-24T00:36:57.4932656Z ##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that's automatically provided by GitHub Actions:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

2. Alternatively, if PROJEN_GITHUB_TOKEN is required for specific permissions:
   - Add the PROJEN_GITHUB_TOKEN to the repository secrets
   - Ensure it has the necessary permissions for pull request operations
   - Verify the token is valid and not expired

3. Verify the token has sufficient permissions to access the GitHub API and perform the required operations on pull requests.
