### ISSUE TITLE
Missing PROJEN_GITHUB_TOKEN in GitHub Actions workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#170]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` that is either not defined or not properly configured in the repository secrets. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the GitHub API is missing or invalid.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Details
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Option 1: Use default GITHUB_TOKEN
1. Update the workflow file to use the default GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN
2. Ensure the token has appropriate permissions for the required operations
3. Replace the github-token line in the pr-triage-manager job with the standard token

Modified code:
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Option 2: Configure PROJEN_GITHUB_TOKEN
If PROJEN_GITHUB_TOKEN is needed for specific permissions:
1. Add the PROJEN_GITHUB_TOKEN secret to the repository settings
2. Ensure it has the appropriate scopes and permissions for pull request operations
