### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#172]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an authentication error. The job is attempting to use `PROJEN_GITHUB_TOKEN` which is either not defined or doesn't have the required permissions.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Details
```
Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that is automatically provided by GitHub Actions
2. Update the pr-triage-manager job in the workflow file to use the correct token
3. Ensure the token has the required permissions for the pull-requests scope

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

This change will use the default GitHub token that is automatically available in all GitHub Actions workflows and has the necessary permissions as defined in the job's `permissions` section.
