### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#178]
## Root Cause Analysis

The GitHub Actions workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job because it's attempting to use a GitHub token named `PROJEN_GITHUB_TOKEN` which is either not defined in the repository secrets or not properly accessible to the workflow.

### Error Details
```
##[error]Parameter token or opts.auth is required
```

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Check if the `PROJEN_GITHUB_TOKEN` secret exists in the repository settings
2. If it doesn't exist, create the secret with appropriate permissions
3. If using a different token is preferred, modify the workflow file to use an available token
4. Update the `pr-triage-manager` job to use the standard `GITHUB_TOKEN` which is automatically available:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

5. Commit the changes and push to the repository
6. Re-run the workflow to verify the fix

## Confidence Level
95% - The error message clearly indicates a missing or invalid authentication token, and the workflow file shows that it's trying to use `PROJEN_GITHUB_TOKEN` which is likely not available.
