### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#180]
## Root Cause Analysis

The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's using an incorrect GitHub token parameter. The job is configured to use `PROJEN_GITHUB_TOKEN` but this token is either not defined in the repository secrets or not properly accessible to the workflow.

## Error Details

**Error Message:**
```
##[error]Parameter token or opts.auth is required
```

**Impacted File:** `.github/workflows/issue-label-assign.yml`

**Problematic Code:**
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's automatically provided by GitHub Actions
2. Update the workflow file to use the correct token
3. Ensure proper permissions are set for the token (already done in the workflow)

### Recommended Code Change:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

This change will use the built-in GitHub token that's automatically available in all GitHub Actions workflows, instead of relying on a custom token that may not be configured.
