### ISSUE TITLE
GitHub Action Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#185]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Description
The GitHub workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job because it's using an incorrect GitHub token. The job is configured to use `PROJEN_GITHUB_TOKEN` which is either not defined or doesn't have the required permissions.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
    parameters: >
      [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's already working for the other jobs.
2. Update the pr-triage-manager job configuration in the workflow file as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

3. Commit and push the changes to the repository.
4. Re-run the workflow to verify that all jobs complete successfully.

### Additional Context
The other jobs in the workflow (`guidance-triage-manager` and `issue-triage-manager`) are using the standard `GITHUB_TOKEN` and are completing successfully. This suggests that the `PROJEN_GITHUB_TOKEN` is either not defined in the repository secrets or doesn't have the necessary permissions.
