### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#206]
## Root Cause Analysis

The GitHub Actions workflow `issue-label-assign.yml` is failing in the `pr-triage-manager` job because it's attempting to use a GitHub token that doesn't exist or isn't properly configured. The job is specifically using `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that's used by the other successful jobs.

### Workflow Status
- **Workflow Run**: https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/actions/runs/15838543438
- **Failed Job**: pr-triage-manager
- **Error**: `Parameter token or opts.auth is required`

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution

1. Update the pr-triage-manager job to use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN
2. Replace the github-token line with: `github-token: "${{ secrets.GITHUB_TOKEN }}"`
3. Commit the changes to the workflow file
4. Re-run the workflow to verify the fix

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Confidence Level
95% - The error message clearly indicates a missing or invalid token, and the workflow configuration shows that the pr-triage-manager job is using a different token than the other successful jobs.
