### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#21]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing GitHub token or authentication parameter. The error message "Parameter token or opts.auth is required" indicates that the `PROJEN_GITHUB_TOKEN` secret referenced in the workflow is not properly configured or available in the repository's secrets.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-23T23:13:29.7843440Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Create the `PROJEN_GITHUB_TOKEN` secret in the repository settings with appropriate permissions
2. Alternatively, modify the workflow file to use the default `GITHUB_TOKEN` which is automatically available in GitHub Actions
3. Update the pr-triage-manager job in the issue-label-assign.yml file to use the correct token:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

4. Commit the changes to the repository
5. Re-run the workflow to verify the fix
