### ISSUE TITLE
GitHub Actions Workflow Failure: Missing Authentication Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#227]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing authentication token. The job is attempting to use a GitHub token named `PROJEN_GITHUB_TOKEN` which is either not defined in the repository secrets or not accessible to the workflow. This results in the error "Parameter token or opts.auth is required" when the aws-issue-triage-manager action tries to authenticate with GitHub.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-24T01:09:54.8734262Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the default `GITHUB_TOKEN` that's automatically provided by GitHub Actions
2. Update the workflow file to use the default token which has the necessary permissions already defined in the job
3. The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

4. Commit the changes to the workflow file
5. Re-run the workflow to verify the fix
