### ISSUE TITLE
GitHub Actions Workflow Failure: Missing Authentication Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#228]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing authentication token. The error message "Parameter token or opts.auth is required" indicates that the GitHub API call is failing because the `PROJEN_GITHUB_TOKEN` secret referenced in the workflow file is not available or not properly configured.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Details
```
2025-06-24T01:11:48.2936491Z ##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Check if the `PROJEN_GITHUB_TOKEN` secret is properly configured in the repository settings.
2. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that is automatically provided by GitHub Actions.
3. Update the workflow file as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

4. Commit and push the changes to the repository.
5. Re-run the workflow to verify that the issue is resolved.
