### ISSUE TITLE
GitHub Actions Workflow Failure: Missing Authentication Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#236]
## Root Cause Analysis

**Confidence Level**: 95%

### Problem Description

The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing GitHub authentication token. The job is attempting to use `PROJEN_GITHUB_TOKEN` which is either not defined in the repository secrets or not properly referenced in the workflow configuration.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Details
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
    parameters: >
      [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Add the PROJEN_GITHUB_TOKEN secret to the repository settings or use the default GITHUB_TOKEN instead
2. Modify the workflow file to use the correct token reference
3. Update the pr-triage-manager job in the issue-label-assign.yml file as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

This change replaces the custom PROJEN_GITHUB_TOKEN with the default GITHUB_TOKEN that's automatically provided by GitHub Actions.
