### ISSUE TITLE
Missing or invalid PROJEN_GITHUB_TOKEN in pr-triage-manager workflow job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#237]
## Root Cause Analysis

The workflow failure is caused by a missing or invalid GitHub token in the pr-triage-manager job. While the issue-triage-manager and guidance-triage-manager jobs use the standard GITHUB_TOKEN secret, the pr-triage-manager job is configured to use a different token called PROJEN_GITHUB_TOKEN which is either not defined in the repository secrets or has expired.

## Impacted File
`.github/workflows/issue-label-assign.yml`

## Error Log
```
##[error]Parameter token or opts.auth is required
```

## Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Update the workflow file to use the standard GITHUB_TOKEN secret instead of PROJEN_GITHUB_TOKEN:
   - Open the .github/workflows/issue-label-assign.yml file
   - Locate the pr-triage-manager job
   - Replace the github-token line with the standard token that works for the other jobs

The corrected code should look like:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

2. If the PROJEN_GITHUB_TOKEN is specifically needed for this job (for example, if it requires elevated permissions), then:
   - Ensure the PROJEN_GITHUB_TOKEN secret is properly defined in the repository settings
   - Verify that the token has not expired
   - Make sure the token has the required permissions for the pull-requests operations
