### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#247]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Description

The GitHub Actions workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job because it's using an incorrect GitHub token parameter. The job is configured to use `PROJEN_GITHUB_TOKEN` secret, but this token is either not defined in the repository secrets or not being passed correctly to the action.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
2025-06-24T01:17:14.6594003Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the default `GITHUB_TOKEN` that's automatically provided by GitHub Actions
2. Update the workflow file to use the correct token reference
3. Ensure the token has the necessary permissions for the action

### Recommended Fix
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

This change will use the default GitHub token that's automatically available in all GitHub Actions workflows, which should have the necessary permissions for the action to function correctly.
