### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#248]
## Root Cause Analysis

The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's using an incorrect GitHub token. The job is trying to use `PROJEN_GITHUB_TOKEN` which is either not defined or doesn't have the required permissions.

## Error Details

```
##[error]Parameter token or opts.auth is required
```

## Impacted File

`.github/workflows/issue-label-assign.yml`

## Problematic Code

```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's available in all GitHub Actions workflows
2. Update the workflow file to use the correct token:

```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

3. If additional permissions are needed beyond what `GITHUB_TOKEN` provides, ensure those permissions are properly configured in the job's permissions section
4. Verify that the workflow has the necessary permissions for pull-requests (which is already correctly set in the current configuration)
