### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in issue-label-assign.yml

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#249]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The workflow failure is caused by an authentication issue in the pr-triage-manager job. The job is using the PROJEN_GITHUB_TOKEN secret, but this token is either missing or invalid, resulting in the error "Parameter token or opts.auth is required" when the aws-issue-triage-manager action attempts to authenticate with GitHub.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-24T01:24:07.8946489Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is automatically provided by GitHub Actions:
   - Open the .github/workflows/issue-label-assign.yml file
   - Locate the pr-triage-manager job
   - Replace the github-token line with: github-token: "${{ secrets.GITHUB_TOKEN }}"
   - This change will ensure the action has proper authentication to interact with GitHub
   
The corrected code should look like:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```
