### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#25]
## Root Cause Analysis

The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` which is either missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the aws-issue-triage-manager action is not being properly provided.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-23T23:17:16.1581139Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that is automatically provided by GitHub Actions
2. Update the workflow file to use the correct token reference
3. Ensure the token has the necessary permissions for the action
4. Modify the pr-triage-manager job in the issue-label-assign.yml file as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Additional Information

- Confidence level: 95%
- The other jobs in the workflow (`issue-triage-manager` and `guidance-triage-manager`) are working correctly because they are using the standard `GITHUB_TOKEN`.
- This issue is likely due to a misconfiguration where the custom token was expected but not properly set up in the repository secrets.
