### ISSUE TITLE
Fix authentication issue in pr-triage-manager job using incorrect GitHub token

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#254]
# Root Cause Analysis: GitHub Actions Workflow Failure

## Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an authentication issue. The job is attempting to use a non-existent secret named `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that was successfully used in the other jobs.

## Confidence Level
95%

## Error Details
```
##[error]Parameter token or opts.auth is required
```

## Impacted File
`.github/workflows/issue-label-assign.yml`

## Problematic Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Root Cause
The workflow failure is caused by an authentication issue in the pr-triage-manager job. The job is using a non-existent secret named PROJEN_GITHUB_TOKEN instead of the standard GITHUB_TOKEN that was successfully used in the other jobs.

## Solution Plan
1. Edit the `.github/workflows/issue-label-assign.yml` file
2. In the pr-triage-manager job, replace the github-token parameter value from `secrets.PROJEN_GITHUB_TOKEN` to `secrets.GITHUB_TOKEN`
3. The corrected code should look like:
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```
4. Commit and push the changes to the repository
5. Re-run the workflow to verify the fix
