### ISSUE TITLE
GitHub Actions Workflow Failure: Authentication Issue in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#255]
# GitHub Actions Workflow Failure: Authentication Issue in PR Triage Manager

## Summary
The workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job due to an authentication issue. The job is attempting to use `PROJEN_GITHUB_TOKEN` which is either not defined or doesn't have the required permissions.

## Root Cause Analysis
- **Confidence Level**: 95%
- **Affected File**: `.github/workflows/issue-label-assign.yml`
- **Error Message**: `##[error]Parameter token or opts.auth is required`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` in the pr-triage-manager job:
   - Open the `.github/workflows/issue-label-assign.yml` file
   - Locate the pr-triage-manager job section
   - Change the github-token parameter from `"${{ secrets.PROJEN_GITHUB_TOKEN }}"` to `"${{ secrets.GITHUB_TOKEN }}"`
   - The corrected code should look like:
   ```yaml
   pr-triage-manager:
     permissions:
       issues: write
       pull-requests: write
     runs-on: ubuntu-latest
     steps:
       - uses: aws-github-ops/aws-issue-triage-manager@main
         with:
           github-token: "${{ secrets.GITHUB_TOKEN }}"
           target: "pull-requests"
           area-is-keyword: true
           default-area: >
             {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
   ```
2. Commit and push the changes to the repository
3. Re-run the workflow to verify the fix works correctly
