### ISSUE TITLE
Fix missing GitHub token in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#267]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing or improperly configured GitHub token in the pr-triage-manager job. The job is attempting to use secrets.PROJEN_GITHUB_TOKEN which is not available, resulting in the error "Parameter token or opts.auth is required".
The pr-triage-manager job is failing because it's trying to use a token that doesn't exist.

### Finding 1: The workflow failure is caused by a missing or improperly configured GitHub token in the pr-triage-manager job. The job is attempting to use secrets.PROJEN_GITHUB_TOKEN which is not available, resulting in the error "Parameter token or opts.auth is required".
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the missing PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is automatically provided by GitHub Actions:
   - Open the .github/workflows/issue-label-assign.yml file
   - Locate the pr-triage-manager job
   - Change the github-token line from:
     github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
     to:
     github-token: "${{ secrets.GITHUB_TOKEN }}"

### Step 3: Re-run the workflow to verify the fix works correctly

Corrected code snippet:
```yaml
  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

---

*Confidence level: 95%*
