### ISSUE TITLE
Fix authentication issue in pr-triage-manager workflow job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#27]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an authentication issue. The job is using the wrong GitHub token variable (`PROJEN_GITHUB_TOKEN`) which is either not defined or doesn't have the required permissions. While the other jobs (`issue-triage-manager` and `guidance-triage-manager`) use the standard `GITHUB_TOKEN` and succeed, the `pr-triage-manager` job fails with the error "Parameter token or opts.auth is required".

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
2025-06-23T23:18:15.5335395Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Modify the pr-triage-manager job in the issue-label-assign.yml workflow file to use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN
2. Update the github-token parameter to use the same token as the other successful jobs
3. The corrected code should be:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```
