### ISSUE TITLE
Workflow Failure: issue-regression-label failing due to non-existent label

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#279]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow is failing because it's trying to remove a label called "potential-regression" from issue #263, but this label doesn't exist in the repository. The GitHub CLI returns an error when attempting to remove a non-existent label.
The GitHub CLI is failing when trying to remove a label that doesn't exist on the issue.

### Finding 1: The workflow is failing because it's trying to remove a label called "potential-regression" from issue #263, but this label doesn't exist in the repository. The GitHub CLI returns an error when attempting to remove a non-existent label.
**Error Log:**

failed to update https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/issues/263: 'potential-regression' not found
failed to update 1 issue
##[error]Process completed with exit code 1.

**Problematic Code:**

if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
  gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
else
  gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
fi

**Impacted File:** `.github/workflows/issue-regression-labeler.yml`

### Step 1: Create the "potential-regression" label in the repository.
The "potential-regression" label needs to be created in the repository.

### Step 2: Modify the workflow to handle cases where the label doesn't exist by checking if the label exists before attempting to remove it. Here's the corrected code:

```yaml
- name: Manage regression label
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
      gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
    else
      # Check if the label exists on the issue before trying to remove it
      if gh issue view ${{ github.event.issue.number }} -R ${{ github.repository }} --json labels --jq '.labels[].name' | grep -q "potential-regression"; then
        gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
      fi
    fi
```

### Step 3: Alternatively, you could create the label programmatically if it doesn't exist:

```yaml
- name: Ensure label exists
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if ! gh label list -R ${{ github.repository }} --json name --jq '.[].name' | grep -q "potential-regression"; then
      gh label create "potential-regression" -c "#fbca04" -d "Issue appears to be a regression" -R ${{ github.repository }}
    fi
```

---

*Confidence level: 95%*
