### ISSUE TITLE
GitHub Actions Workflow Failure: Incorrect GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#283]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The root cause of the workflow failure is that the "pr-triage-manager" job is using a non-existent GitHub token secret named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully by the other jobs.
The workflow is failing because it's trying to use a token that doesn't exist in the repository secrets.

### Finding 1: The root cause of the workflow failure is that the "pr-triage-manager" job is using a non-existent GitHub token secret named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully by the other jobs.
**Error Log:**

2025-06-24T01:37:42.9315454Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Modify the workflow file to use the standard GITHUB_TOKEN secret instead of PROJEN_GITHUB_TOKEN
The workflow file needs to be updated to use the correct token.

### Step 2: Open the .github/workflows/issue-label-assign.yml file
Locate the file that needs to be modified.

### Step 3: Locate the pr-triage-manager job section
Find the specific job that's failing.

### Step 4: Replace the github-token line with the correct token reference
Update the token reference to use the standard GitHub token.

### Step 5: Save the file and commit the changes
Commit the updated workflow file.

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

---

*Confidence level: 95%*
