### ISSUE TITLE
GitHub Action Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#287]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing GitHub token. The pr-triage-manager job is configured to use a non-existent secret called "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully by the other jobs.
The workflow is failing because it's trying to use a token that doesn't exist in the repository secrets.

### Finding 1: The workflow failure is caused by a missing GitHub token. The pr-triage-manager job is configured to use a non-existent secret called "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully by the other jobs.
**Error Log:**

2025-06-24T01:42:47.3174598Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 3: The corrected code should be:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Step 5: Re-run the workflow to verify the fix

---

*Confidence level: 95%*
