### ISSUE TITLE
Fix missing GitHub token in pr-triage-manager workflow job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#295]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing GitHub token in the pr-triage-manager job. The job is attempting to use a non-existent secret called PROJEN_GITHUB_TOKEN, resulting in the error "Parameter token or opts.auth is required".
The workflow is trying to use a secret that doesn't exist in the repository.

### Finding 1: The workflow failure is caused by a missing GitHub token in the pr-triage-manager job. The job is attempting to use a non-existent secret called PROJEN_GITHUB_TOKEN, resulting in the error "Parameter token or opts.auth is required".
**Error Log:**

2025-06-24T01:44:15.9346668Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the non-existent PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is available by default in GitHub Actions
The workflow should use the standard GITHUB_TOKEN instead of a custom token.

### Step 2: Update the pr-triage-manager job in the workflow file to use the correct token
Modify the workflow file to use the correct token.

### Step 3: The corrected code should look like:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 4: Commit the changes to the repository
Apply the changes to the repository.

### Step 5: Re-run the workflow to verify the fix
Verify that the workflow runs successfully after the changes.

---

*Confidence level: 95%*
