### ISSUE TITLE
Fix GitHub workflow authentication token in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#302]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The root cause of the workflow failure is in the "pr-triage-manager" job where it's using a non-existent secret named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that's being used successfully in the other jobs. The GitHub Action requires an authentication token to interact with the GitHub API, and when this token is missing or invalid, it fails with the error "Parameter token or opts.auth is required".
The workflow is failing because it's trying to use a non-existent secret for authentication.

### Finding 1: The root cause of the workflow failure is in the "pr-triage-manager" job where it's using a non-existent secret named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that's being used successfully in the other jobs. The GitHub Action requires an authentication token to interact with the GitHub API, and when this token is missing or invalid, it fails with the error "Parameter token or opts.auth is required".
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 4: Replace the github-token line with the correct token reference.

Here's the corrected code:

```yaml
  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

This change will ensure the pr-triage-manager job has the proper authentication token to interact with the GitHub API, just like the other successful jobs in the workflow.

---

*Confidence level: 95%*
