### ISSUE TITLE
Fix authentication issue in pr-triage-manager job using incorrect GitHub token

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#303]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by an authentication issue in the pr-triage-manager job. The job is using a non-existent GitHub token named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully in the other jobs.
The pr-triage-manager job is failing due to an authentication issue with the GitHub token.

### Finding 1: The workflow failure is caused by an authentication issue in the pr-triage-manager job. The job is using a non-existent GitHub token named "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully in the other jobs.
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the non-existent PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is available in all GitHub Actions workflows.
The pr-triage-manager job in the issue-label-assign.yml file should be updated.

### Step 2: Update the pr-triage-manager job in the issue-label-assign.yml file as follows:

```yaml
  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 3: Commit and push the changes to the repository.
Commit and push the changes to the repository.

### Step 4: Re-run the workflow to verify that all jobs now complete successfully.
Re-run the workflow to verify that all jobs now complete successfully.

---

*Confidence level: 95%*
