### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#320]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow is failing because the "pr-triage-manager" job is using a non-existent or invalid GitHub token. The error message "Parameter token or opts.auth is required" indicates that the GitHub token specified in the workflow configuration is not being properly passed to the GitHub API.
The workflow is using a non-existent GitHub token which is causing authentication failures.

### Finding 1: The workflow is failing because the "pr-triage-manager" job is using a non-existent or invalid GitHub token. The error message "Parameter token or opts.auth is required" indicates that the GitHub token specified in the workflow configuration is not being properly passed to the GitHub API.
**Error Log:**

2025-06-24T01:59:10.8122361Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the non-existent "PROJEN_GITHUB_TOKEN" with the standard "GITHUB_TOKEN" that's automatically provided by GitHub Actions.
The corrected code should be:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 3: Make sure the token has the necessary permissions to access pull request data.

---

*Confidence level: 95%*
