### ISSUE TITLE
GitHub Actions Workflow Failure: Incorrect GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#322]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by using an incorrect GitHub token secret name in the pr-triage-manager job. The job is using "PROJEN_GITHUB_TOKEN" which is either not defined or not accessible in the repository secrets.
The issue-label-assign.yml workflow is failing because it's trying to use a token that doesn't exist or isn't accessible.

### Finding 1: The workflow failure is caused by using an incorrect GitHub token secret name in the pr-triage-manager job. The job is using "PROJEN_GITHUB_TOKEN" which is either not defined or not accessible in the repository secrets.
**Error Log:**

2025-06-24T01:57:58.0806281Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the incorrect GitHub token reference with the standard GITHUB_TOKEN that is available by default in GitHub Actions
The workflow should use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN.

### Step 2: Update the pr-triage-manager job in the workflow file to use the correct token
Modify the workflow file to use the correct token.

### Step 3: Change the line `github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"` to `github-token: "${{ secrets.GITHUB_TOKEN }}"`
Update the token reference in the workflow file.

### Step 4: Commit the changes to the repository
Apply the changes to the repository.

### Step 5: Re-run the workflow to verify the fix
Test the workflow after making the changes.

The corrected code should look like:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

---

*Confidence level: 95%*
