### ISSUE TITLE
Fix issue-regression-labeler workflow failing when removing non-existent label

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#327]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow is failing because it's trying to remove a label "potential-regression" that doesn't exist on the issue. The GitHub CLI (gh) command fails when attempting to remove a non-existent label from an issue.
The issue-regression-labeler.yml workflow is failing when trying to remove a non-existent label.

### Finding 1: The workflow is failing because it's trying to remove a label "potential-regression" that doesn't exist on the issue. The GitHub CLI (gh) command fails when attempting to remove a non-existent label from an issue.
**Error Log:**

failed to update https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/issues/301: 'potential-regression' not found
failed to update 1 issue
##[error]Process completed with exit code 1.

**Problematic Code:**

- name: Manage regression label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
          gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
        else
          gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
        fi

**Impacted File:** `.github/workflows/issue-regression-labeler.yml`

### Step 3: Replace the current implementation with the following code:

```yaml
- name: Manage regression label
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
      gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
    else
      # Check if the label exists on the issue before trying to remove it
      if gh issue view ${{ github.event.issue.number }} -R ${{ github.repository }} --json labels --jq '.labels[].name' | grep -q "potential-regression"; then
        gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
      fi
    fi
```

### Step 4: Alternatively, you could also create the label in the repository first if it doesn't exist:
```yaml
- name: Ensure label exists
  if: steps.check_regression.outputs.is_regression == 'true'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    # Create the label if it doesn't exist
    gh label create "potential-regression" --color "#fbca04" --description "Issue appears to be a regression" -R ${{ github.repository }} || true
```

---

*Confidence level: 95%*
