### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#330]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow is failing because the GitHub token specified in the pr-triage-manager job is missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the aws-github-ops/aws-issue-triage-manager action is not being properly provided.
The issue-label-assign.yml workflow is failing due to authentication problems with the GitHub token.

### Finding 1: The workflow is failing because the GitHub token specified in the pr-triage-manager job is missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the authentication token needed by the aws-github-ops/aws-issue-triage-manager action is not being properly provided.
**Error Log:**

2025-06-24T02:01:12.4143138Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Verify that the PROJEN_GITHUB_TOKEN secret exists in the repository settings
The PROJEN_GITHUB_TOKEN secret may be missing from the repository.

### Step 2: If the secret doesn't exist, create it with appropriate permissions
Create the PROJEN_GITHUB_TOKEN with necessary permissions if it doesn't exist.

### Step 3: If you don't have access to create this specific token, use the default GITHUB_TOKEN instead
If you can't create the specific token, use the default one provided by GitHub.

### Step 4: Update the workflow file to use the correct token:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Step 5: Commit and push the changes to trigger the workflow again
Push the changes to the repository to trigger a new workflow run.

### Step 6: Monitor the workflow run to ensure it completes successfully
Check the Actions tab to verify the workflow runs without errors.

---

*Confidence level: 95%*
