### ISSUE TITLE
GitHub Action Failure: Missing PROJEN_GITHUB_TOKEN in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#335]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow is failing because the pr-triage-manager job is using a non-existent GitHub token. The job is configured to use "PROJEN_GITHUB_TOKEN" but this token is either not defined in the repository secrets or not accessible, resulting in an authentication error.
The workflow is attempting to use a token that doesn't exist or isn't accessible, causing authentication failures.

### Finding 1: The workflow is failing because the pr-triage-manager job is using a non-existent GitHub token. The job is configured to use "PROJEN_GITHUB_TOKEN" but this token is either not defined in the repository secrets or not accessible, resulting in an authentication error.
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the non-existent PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is automatically provided by GitHub Actions
The workflow should use the standard token that's automatically available.

### Step 2: Update the workflow file to use the correct token reference
Update the token reference in the workflow file.

### Step 3: Ensure proper permissions are set for the token
Verify that the permissions are correctly configured.

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

This change ensures the workflow uses the standard GitHub token that's automatically available in all workflows.

---

*Confidence level: 95%*
