### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#337]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The root cause of the workflow failure is an authentication issue in the pr-triage-manager job. The job is using the secret "PROJEN_GITHUB_TOKEN" which is either missing or invalid, resulting in the error "Parameter token or opts.auth is required" when the aws-issue-triage-manager action attempts to authenticate with GitHub.
The workflow is failing due to an authentication issue with the GitHub token.

### Finding 1: The root cause of the workflow failure is an authentication issue in the pr-triage-manager job. The job is using the secret "PROJEN_GITHUB_TOKEN" which is either missing or invalid, resulting in the error "Parameter token or opts.auth is required" when the aws-issue-triage-manager action attempts to authenticate with GitHub.
**Error Log:**

2025-06-24T02:06:40.3449963Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
            

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the missing or invalid PROJEN_GITHUB_TOKEN with the standard GITHUB_TOKEN that is automatically provided by GitHub Actions:

```yaml
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 2: Alternatively, if PROJEN_GITHUB_TOKEN is required for specific permissions:
   - Ensure the PROJEN_GITHUB_TOKEN secret is properly configured in the repository settings
   - Verify that the token has the necessary permissions for pull request operations

### Step 3: If using a custom token is necessary, make sure it's properly set up in the repository secrets with appropriate scopes for pull request operations.

---

*Confidence level: 95%*
