### ISSUE TITLE
GitHub Actions PR Labeler Workflow Failure - Missing Labels and Insufficient Permissions

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#342]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The "auto-approve" job fails because the label "auto-approve" does not exist in the repository. The GitHub CLI command attempts to add a label that hasn't been created yet in the repository.
The GitHub CLI command is trying to add a label that doesn't exist in the repository.

### 2. The "copy-labels" job fails because the GitHub token used by the cdklabs/pr-triage-manager action doesn't have sufficient permissions to create labels on the repository. The error indicates an "unauthorized" response when attempting to create or apply the "p2" label.
The workflow doesn't have sufficient permissions to create labels.

### Finding 1: The "auto-approve" job fails because the label "auto-approve" does not exist in the repository. The GitHub CLI command attempts to add a label that hasn't been created yet in the repository.
**Error Log:**

'auto-approve' not found
##[error]Process completed with exit code 1.

**Problematic Code:**

      - run: gh pr edit ${{ github.event.pull_request.number }} --add-label "auto-approve" -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Impacted File:** `.github/workflows/pr-labeler.yml`

### Finding 2: The "copy-labels" job fails because the GitHub token used by the cdklabs/pr-triage-manager action doesn't have sufficient permissions to create labels on the repository. The error indicates an "unauthorized" response when attempting to create or apply the "p2" label.
**Error Log:**

##[error]You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}

**Problematic Code:**

  copy-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: cdklabs/pr-triage-manager@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

**Impacted File:** `.github/workflows/pr-labeler.yml`

### Step 3: Update the workflow file to handle missing labels gracefully:

```yaml
      - name: Add auto-approve label
        run: |
          # Check if label exists, create if not
          if ! gh label list -R ${{ github.repository }} | grep -q "auto-approve"; then
            gh label create "auto-approve" -c "#0E8A16" -d "Automatically approved PR" -R ${{ github.repository }}
          fi
          # Add label to PR
          gh pr edit ${{ github.event.pull_request.number }} --add-label "auto-approve" -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Step 1: Update the permissions section in the workflow to include "contents" write permission, which is required for label management:

```yaml
  copy-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - uses: cdklabs/pr-triage-manager@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

### Step 2: Alternatively, if using a custom token with higher privileges is an option:

```yaml
  copy-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: cdklabs/pr-triage-manager@main
        with:
          github-token: ${{ secrets.HIGHER_PRIVILEGE_TOKEN }}
```

### Step 3: Ensure that the repository settings allow the GitHub Actions workflow to create and manage labels

---

*Confidence level: 95%*
