### ISSUE TITLE
GitHub Workflow Failure: Missing or Invalid GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#343]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The GitHub workflow "Set Issue Label and Assignee" is failing in the "pr-triage-manager" job because the required GitHub token parameter is missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the action is trying to authenticate with GitHub but cannot find valid credentials.
The workflow is failing because it's missing a valid GitHub token for authentication.

### Finding 1: The GitHub workflow "Set Issue Label and Assignee" is failing in the "pr-triage-manager" job because the required GitHub token parameter is missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the action is trying to authenticate with GitHub but cannot find valid credentials.
**Error Log:**

2025-06-24T02:04:06.1582594Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
            

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 4: Update the workflow file as follows:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 6: Re-run the workflow to verify that the issue is resolved.

---

*Confidence level: 95%*
