### ISSUE TITLE
Missing GitHub token in pr-triage-manager job causes workflow failure

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#344]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing GitHub token in the pr-triage-manager job. The job is attempting to use a non-existent secret called "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully in the other jobs.
The workflow is failing because it's trying to use a token that doesn't exist in the repository.

### Finding 1: The workflow failure is caused by a missing GitHub token in the pr-triage-manager job. The job is attempting to use a non-existent secret called "PROJEN_GITHUB_TOKEN" instead of the standard "GITHUB_TOKEN" that is used successfully in the other jobs.
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 2: Modify the github-token parameter in the pr-triage-manager job as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 3: If a custom token with different permissions is actually needed, ensure the PROJEN_GITHUB_TOKEN secret is properly configured in the repository settings

---

*Confidence level: 95%*
