### ISSUE TITLE
Missing GitHub Token in PR Triage Manager Workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#345]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing authentication token in the pr-triage-manager job. The error message "Parameter token or opts.auth is required" indicates that the GitHub token specified in the workflow configuration is not available or not properly configured.
The workflow is failing because the required GitHub token is not available or properly configured.

### Finding 1: The workflow failure is caused by a missing authentication token in the pr-triage-manager job. The error message "Parameter token or opts.auth is required" indicates that the GitHub token specified in the workflow configuration is not available or not properly configured.
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Check if the secret PROJEN_GITHUB_TOKEN exists in the repository secrets.
The secret PROJEN_GITHUB_TOKEN needs to be verified in the repository settings.

### Step 2: If the secret doesn't exist, create it with appropriate permissions.
Create the PROJEN_GITHUB_TOKEN with the necessary permissions if it doesn't exist.

### Step 3: Alternatively, modify the workflow to use the default GITHUB_TOKEN which is automatically available:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 4: Commit the changes to the workflow file.
Update the workflow file with the changes and commit them to the repository.

### Step 5: Re-run the workflow to verify the fix.
Trigger the workflow again to ensure the authentication issue is resolved.

---

*Confidence level: 95%*
