### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#35]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's using a GitHub token named `PROJEN_GITHUB_TOKEN` that is either not defined in the repository secrets or doesn't have the required permissions. The error message "Parameter token or opts.auth is required" indicates that the authentication token is missing or invalid when the aws-github-ops/aws-issue-triage-manager action attempts to use it.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-23T23:22:37.3626998Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom `PROJEN_GITHUB_TOKEN` with the default `GITHUB_TOKEN` that's automatically provided by GitHub Actions:
   - Open the workflow file `.github/workflows/issue-label-assign.yml`
   - Locate the `pr-triage-manager` job
   - Replace the github-token line with the standard GitHub token

2. Updated code:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

3. Commit the changes to the repository
4. Re-run the workflow to verify the fix works properly
