### ISSUE TITLE
Fix GitHub Actions workflow failure in pr-triage-manager job due to missing PROJEN_GITHUB_TOKEN

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#351]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The root cause of the workflow failure is that the pr-triage-manager job is using a non-existent secret named PROJEN_GITHUB_TOKEN instead of the standard GITHUB_TOKEN that is used successfully in the other jobs.
The workflow is failing because it's trying to use a secret that doesn't exist in the repository.

### Finding 1: The root cause of the workflow failure is that the pr-triage-manager job is using a non-existent secret named PROJEN_GITHUB_TOKEN instead of the standard GITHUB_TOKEN that is used successfully in the other jobs.
**Error Log:**

2025-06-24T02:12:53.3386309Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Edit the .github/workflows/issue-label-assign.yml file
Edit the workflow file to use the correct token.

### Step 2: In the pr-triage-manager job, replace the github-token parameter value with the standard GITHUB_TOKEN
Update the token reference to use the standard token.

### Step 3: The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 4: Commit and push the changes to the repository
Apply the changes to the repository.

### Step 5: Re-run the workflow to verify the fix
Verify that the workflow runs successfully after the changes.

---

*Confidence level: 95%*
