### ISSUE TITLE
Missing GitHub Token in PR Triage Manager Workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#361]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow failure is caused by a missing GitHub token parameter in the pr-triage-manager job. The error message "Parameter token or opts.auth is required" indicates that the aws-issue-triage-manager action is not receiving a valid authentication token because the secret "PROJEN_GITHUB_TOKEN" is not defined or accessible in the repository.
The workflow is failing because it's trying to use a token that doesn't exist or isn't accessible.

### Finding 1: The workflow failure is caused by a missing GitHub token parameter in the pr-triage-manager job. The error message "Parameter token or opts.auth is required" indicates that the aws-issue-triage-manager action is not receiving a valid authentication token because the secret "PROJEN_GITHUB_TOKEN" is not defined or accessible in the repository.
**Error Log:**

2025-06-24T02:16:08.1964027Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the custom PROJEN_GITHUB_TOKEN with the default GITHUB_TOKEN that's automatically provided by GitHub Actions
The workflow should use the default token instead of a custom one.

### Step 2: Update the pr-triage-manager job in the workflow file to use the default token
Update the workflow file with the correct token reference.

### Step 3: Ensure the token has the necessary permissions for the action
Make sure the permissions are correctly configured.

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

---

*Confidence level: 95%*
