### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#366]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The workflow fails because the pr-triage-manager job is using a non-existent GitHub token. The job attempts to use "PROJEN_GITHUB_TOKEN" which is not available in the environment, resulting in an authentication error.
The workflow is attempting to use a token that doesn't exist in the GitHub Actions environment.

### Finding 1: The workflow fails because the pr-triage-manager job is using a non-existent GitHub token. The job attempts to use "PROJEN_GITHUB_TOKEN" which is not available in the environment, resulting in an authentication error.
**Error Log:**

2025-06-24T02:22:23.0050678Z ##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the non-existent "PROJEN_GITHUB_TOKEN" with the standard "GITHUB_TOKEN" that is available by default in GitHub Actions
The workflow should use the standard GitHub token instead of a custom one.

### Step 2: Update the workflow file to use the correct token reference
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Step 3: Commit the changes to the repository
Apply the changes to the workflow file in the repository.

---

*Confidence level: 95%*
