### ISSUE TITLE
GitHub Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#37]
# Root Cause Analysis: GitHub Workflow Failure

## Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing or improperly configured GitHub token.

## Confidence Level
95%

## Analysis
The root cause of the workflow failure is that the pr-triage-manager job is using a non-existent or improperly configured GitHub token. While the other jobs use the default GITHUB_TOKEN secret which is automatically provided by GitHub Actions, the pr-triage-manager job is configured to use a custom token called PROJEN_GITHUB_TOKEN which is either not defined in the repository secrets or doesn't have the required permissions.

## Impacted File
`.github/workflows/issue-label-assign.yml`

## Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Error Log
```
2025-06-23T23:21:10.3064489Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the custom PROJEN_GITHUB_TOKEN with the default GITHUB_TOKEN that's automatically provided by GitHub Actions:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

2. Alternatively, if a custom token with specific permissions is required, ensure the PROJEN_GITHUB_TOKEN secret is properly defined in the repository settings with the appropriate scopes and permissions.

3. Verify that the token has the required permissions for the operations being performed (issues:write and pull-requests:write).

4. After making these changes, re-run the workflow to verify the fix.
