### ISSUE TITLE
Fix GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#370]
## Troubleshooting
After analyzing the workflow run logs and the source code, I've identified the following findings and the appropriate solution plan:

### 1. The root cause of the workflow failure is that the pr-triage-manager job is attempting to use a non-existent or inaccessible GitHub token named "PROJEN_GITHUB_TOKEN". Unlike the other jobs which use the standard "GITHUB_TOKEN", this job is configured to use a custom token that is not available in the environment.
The pr-triage-manager job in the issue-label-assign.yml workflow is failing because it's trying to use a token that doesn't exist in the environment.

### Finding 1: The root cause of the workflow failure is that the pr-triage-manager job is attempting to use a non-existent or inaccessible GitHub token named "PROJEN_GITHUB_TOKEN". Unlike the other jobs which use the standard "GITHUB_TOKEN", this job is configured to use a custom token that is not available in the environment.
**Error Log:**

##[error]Parameter token or opts.auth is required

**Problematic Code:**

  pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]

**Impacted File:** `.github/workflows/issue-label-assign.yml`

### Step 1: Replace the custom token with the standard GitHub token that is available in all GitHub Actions workflows
The workflow should use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN.

### Step 2: Update the pr-triage-manager job in the issue-label-assign.yml file to use the standard GITHUB_TOKEN
Change the token reference in the workflow file.

### Step 3: The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Step 4: Commit and push the changes to the repository
Apply the changes to the repository.

### Step 5: Re-run the workflow to verify that all jobs now succeed
Verify the fix by running the workflow again.

---

*Confidence level: 95%*
