### ISSUE TITLE
GitHub Workflow Failure: Invalid GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#39]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Description

The `pr-triage-manager` job in the GitHub workflow is failing because it's using a non-existent or invalid GitHub token named `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that works for the other jobs.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the non-existent `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that works for the other jobs
2. Modify the pr-triage-manager job in the workflow file to use the correct token
3. The corrected code should be:
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```
4. Commit and push the changes to the repository
5. Re-run the workflow to verify the fix works
