### ISSUE TITLE
Fix missing GitHub token in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#42]
## Root Cause Analysis

The workflow run [#15837283717](https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/actions/runs/15837283717) is failing in the `pr-triage-manager` job with the error:

```
##[error]Parameter token or opts.auth is required
```

### Analysis

The `pr-triage-manager` job is failing because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` which is not available in the environment. The error message indicates that the authentication token needed by the `aws-github-ops/aws-issue-triage-manager` action is missing or invalid.

### Impacted File

`.github/workflows/issue-label-assign.yml`

### Problematic Code

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Solution Plan

1. Replace the non-existent `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that is automatically available in GitHub Actions workflows
2. Update the `github-token` parameter in the `pr-triage-manager` job to use the standard token
3. Ensure the token has the necessary permissions (which are already correctly set in the workflow)

### Corrected Code

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Confidence Level

**95%** - The error message clearly indicates a missing or invalid authentication token, and the workflow file shows that a non-standard token name is being used.
