### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid GitHub Token in pr-triage-manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#53]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The "pr-triage-manager" job in the GitHub Actions workflow is failing because the GitHub token parameter is missing or invalid. The error message "Parameter token or opts.auth is required" indicates that the GitHub API call is failing due to missing authentication credentials.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
2025-06-23T23:29:50.5627836Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Check if the PROJEN_GITHUB_TOKEN secret exists in the repository settings
2. If the secret doesn't exist, create it with appropriate permissions
3. Alternatively, use the default GITHUB_TOKEN that's automatically provided by GitHub Actions
4. Update the workflow file to use the correct token:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

This change will use the default GitHub token that's automatically available in all GitHub Actions workflows, which should have the necessary permissions to perform the required operations.
