### ISSUE TITLE
GitHub Actions Workflow Failure: Missing Authentication Token in PR Triage Manager

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#54]
### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job with the error: `Parameter token or opts.auth is required`. This indicates a missing or improperly configured authentication token.

### Analysis
The workflow failure is caused by a missing authentication token in the pr-triage-manager job. The error message "Parameter token or opts.auth is required" indicates that the GitHub token specified in the workflow file is not available or not properly configured. 

The job is using a different token (`PROJEN_GITHUB_TOKEN`) than the other successful jobs which use the standard `GITHUB_TOKEN`. It appears that the `PROJEN_GITHUB_TOKEN` secret is either not defined in the repository secrets or not accessible to the workflow.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
2025-06-23T23:29:45.1703568Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Change the GitHub token used in the pr-triage-manager job to use the same GITHUB_TOKEN that works for the other jobs.
2. Ensure that the repository has the GITHUB_TOKEN secret properly configured.
3. Update the workflow file by replacing the token reference with the standard token.

Here's the corrected code:
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

4. Commit and push the changes to the repository.
5. Re-run the workflow to verify the fix.

## Confidence Level
**95%** - The error message clearly indicates a missing token issue, and the solution is to use the standard GitHub token that works in the other jobs.
