### ISSUE TITLE
GitHub Actions Workflow Failure: Missing GitHub Token in PR Triage Manager Job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#58]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to a missing GitHub token. The job is attempting to use a non-existent secret called `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that is used successfully in the other jobs.

### Affected Resources
- **File Path**: `.github/workflows/issue-label-assign.yml`
- **Job**: `pr-triage-manager`

### Error Details
```
##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Steps to Fix
1. Update the workflow file to use the standard `GITHUB_TOKEN` secret that is automatically provided by GitHub Actions
2. Replace the `github-token` parameter in the `pr-triage-manager` job with the correct token

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Implementation Plan
1. Commit and push the changes to the repository
2. Re-run the workflow to verify the fix

### Additional Notes
The other jobs in the workflow (`guidance-triage-manager` and `issue-triage-manager`) are working correctly because they are using the standard `GITHUB_TOKEN` secret.
