### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#59]
## Root Cause Analysis

The workflow `Set Issue Label and Assignee` is failing in the `pr-triage-manager` job due to a missing or invalid GitHub token.

### Error Details
```
##[error]Parameter token or opts.auth is required
```

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Analysis
The root cause of the workflow failure is that the "pr-triage-manager" job is using a non-existent GitHub token. The job is configured to use "PROJEN_GITHUB_TOKEN" secret, but this token is either not defined in the repository secrets or has expired/been revoked, resulting in an authentication error.

While the other jobs in the same workflow are using the default `GITHUB_TOKEN` and working correctly, this specific job is failing because it's trying to use a custom token that doesn't exist.

## Solution

1. Replace the non-existent "PROJEN_GITHUB_TOKEN" with the default "GITHUB_TOKEN" that is automatically provided by GitHub Actions.
2. Update the workflow file to use the correct token.
3. Ensure the token has the necessary permissions (which are already correctly set in the job).

### Corrected Code
```yaml
- uses: aws-github-ops/aws-issue-triage-manager@main
  with:
    github-token: "${{ secrets.GITHUB_TOKEN }}"
    target: "pull-requests"
    area-is-keyword: true
    default-area: >
      {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

This change will allow the workflow to use the default GitHub token that is automatically available in all GitHub Actions workflows, which has the necessary permissions to perform the required operations.
