### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#63]
## Root Cause Analysis

The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job because it's attempting to use a non-existent GitHub token named `PROJEN_GITHUB_TOKEN` instead of the standard `GITHUB_TOKEN` that is used successfully in the other jobs.

### Error Message
```
Parameter token or opts.auth is required
```

### Affected File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution

1. Edit the `.github/workflows/issue-label-assign.yml` file
2. In the `pr-triage-manager` job, replace the `github-token` parameter value with the standard `GITHUB_TOKEN`
3. The corrected code should look like this:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

4. Commit and push the changes to trigger the workflow again
5. Verify that all jobs complete successfully

## Additional Context

The other two jobs in the workflow (`issue-triage-manager` and `guidance-triage-manager`) are using the standard `GITHUB_TOKEN` and are completing successfully. This confirms that the issue is with the token name in the `pr-triage-manager` job.

Confidence level: 95%
