### ISSUE TITLE
Fix GitHub token configuration in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#65]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The workflow job "pr-triage-manager" is failing because it's using a non-existent or invalid GitHub token. The job is configured to use "secrets.PROJEN_GITHUB_TOKEN" while the other successful jobs are using "secrets.GITHUB_TOKEN". The error message "Parameter token or opts.auth is required" indicates that the authentication token is missing or invalid when the aws-issue-triage-manager action tries to authenticate with GitHub.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the non-existent "PROJEN_GITHUB_TOKEN" with the standard "GITHUB_TOKEN" that's automatically provided by GitHub Actions.
2. Modify the pr-triage-manager job in the issue-label-assign.yml file to use the correct token.
3. The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

4. If a custom token with specific permissions is actually needed, ensure the PROJEN_GITHUB_TOKEN secret is properly configured in the repository settings.
