### ISSUE TITLE
GitHub Action Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#66]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub workflow "Set Issue Label and Assignee" is failing in the "pr-triage-manager" job because it's attempting to use a GitHub token named "PROJEN_GITHUB_TOKEN" that is not defined or accessible in the repository's secrets. The error message "Parameter token or opts.auth is required" indicates that the authentication token required by the aws-issue-triage-manager action is missing or invalid.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the non-existent "PROJEN_GITHUB_TOKEN" with the standard "GITHUB_TOKEN" that is automatically provided by GitHub Actions.
2. Update the workflow file to use the correct token reference.
3. If a custom token with specific permissions is needed, ensure it's properly defined in the repository secrets.

### Corrected Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

Note that this solution assumes the standard GITHUB_TOKEN has sufficient permissions for the required operations. If additional permissions are needed, you may need to create a custom Personal Access Token (PAT) with the appropriate scopes and add it to the repository secrets.
