### ISSUE TITLE
GitHub Action Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#67]
## Root Cause Analysis

**Confidence Level:** 95%

### Problem Description
The workflow run [#15837482407](https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/actions/runs/15837482407) is failing in the `pr-triage-manager` job due to an authentication issue. The job is using the `PROJEN_GITHUB_TOKEN` secret which is either not defined or not properly configured in the repository secrets.

### Error Message
```
##[error]Parameter token or opts.auth is required
```

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Add the PROJEN_GITHUB_TOKEN secret to the repository secrets in GitHub:
   - Go to the repository settings
   - Navigate to Secrets and variables > Actions
   - Add a new repository secret named PROJEN_GITHUB_TOKEN with a valid GitHub token value

2. Alternatively, modify the workflow file to use the default GITHUB_TOKEN instead:
   - Open the .github/workflows/issue-label-assign.yml file
   - Replace the github-token line in the pr-triage-manager job with:
     ```yaml
     github-token: "${{ secrets.GITHUB_TOKEN }}"
     ```
   
3. If the PROJEN_GITHUB_TOKEN is required for specific permissions not available in GITHUB_TOKEN:
   - Ensure the token has the necessary permissions for pull request operations
   - Verify the token hasn't expired
   - Check that the token is properly formatted

4. Commit the changes to the repository and trigger the workflow again
