### ISSUE TITLE
GitHub Actions Workflow Failure: Missing or Invalid PROJEN_GITHUB_TOKEN in issue-label-assign.yml

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#71]
### Summary
The `pr-triage-manager` job in the `issue-label-assign.yml` workflow is failing because it's using `PROJEN_GITHUB_TOKEN` which is either not defined or doesn't have the required permissions. The error message "Parameter token or opts.auth is required" indicates that the GitHub token being passed to the GitHub API is empty or invalid.

### Confidence Level
95%

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
2025-06-23T23:44:07.4836390Z ##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that's automatically provided by GitHub Actions
2. Update the workflow file to use the correct token:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

3. If a custom token with specific permissions is needed, ensure the `PROJEN_GITHUB_TOKEN` secret is properly defined in the repository settings
4. Verify that the token has the required permissions for the operations being performed (`issues:write` and `pull-requests:write`)
