### ISSUE TITLE
GitHub Workflow Failure: issue-regression-label fails when removing non-existent label

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#77]
# Root Cause Analysis: GitHub Workflow Failure

## Summary
The GitHub workflow `issue-regression-label` is failing because it attempts to remove a label "potential-regression" that doesn't exist on the issue. The GitHub CLI command returns an error when trying to remove a non-existent label, causing the workflow to fail with exit code 1.

## Error Details
```
failed to update https://github.com/CloudSmith-Delivery-Troubleshooting/aws-cdk-/issues/46: 'potential-regression' not found
failed to update 1 issue
##[error]Process completed with exit code 1.
```

## Impacted File
`.github/workflows/issue-regression-labeler.yml`

## Problematic Code
```yaml
if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
  gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
else
  gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
fi
```

### Option 1: Add Error Handling
Modify the workflow to handle the case when a label doesn't exist by adding error handling to the remove-label command:

```yaml
- name: Manage regression label
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
      # Add the label if regression is detected
      gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
    else
      # Try to remove the label, but don't fail if it doesn't exist
      gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }} || true
    fi
```

The `|| true` part ensures that even if the gh command fails (because the label doesn't exist), the overall step will still succeed.

### Option 2: Check if Label Exists Before Removing
Alternatively, check if the label exists before attempting to remove it:

```yaml
- name: Manage regression label
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    if [ "${{ steps.check_regression.outputs.is_regression }}" == "true" ]; then
      gh issue edit ${{ github.event.issue.number }} --add-label "potential-regression" -R ${{ github.repository }}
    else
      # Check if label exists before removing
      if gh issue view ${{ github.event.issue.number }} -R ${{ github.repository }} --json labels | grep -q "potential-regression"; then
        gh issue edit ${{ github.event.issue.number }} --remove-label "potential-regression" -R ${{ github.repository }}
      fi
    fi
```

## Confidence Level
95% - The error message clearly indicates that the workflow is attempting to remove a label that doesn't exist, and the workflow code confirms this behavior.
