### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#84]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub workflow is failing because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` that is either missing or not properly configured in the repository secrets.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

### Solution Plan

1. Update the pr-triage-manager job in the workflow file to use the default GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN:
   - Open the .github/workflows/issue-label-assign.yml file
   - Locate the pr-triage-manager job section
   - Replace the github-token line with: github-token: "${{ secrets.GITHUB_TOKEN }}"
   - This change will make the pr-triage-manager job use the same token as the other jobs that are working correctly
   - The corrected code should look like:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

2. If PROJEN_GITHUB_TOKEN is specifically needed for some reason (like elevated permissions), then add it to the repository secrets:
   - Go to the repository settings
   - Navigate to Secrets and variables > Actions
   - Add a new repository secret named PROJEN_GITHUB_TOKEN with the appropriate token value
