### ISSUE TITLE
GitHub Actions Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#85]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub Actions workflow is failing because it's using a GitHub token named `PROJEN_GITHUB_TOKEN` that is either missing or doesn't have the required permissions. The error message "Parameter token or opts.auth is required" indicates that the authentication token is not being properly passed to the GitHub API.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
2025-06-23T23:46:00.4950198Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` that is automatically provided by GitHub Actions
2. Update the workflow file to use the correct token reference
3. Ensure the token has the necessary permissions for pull request operations

### Recommended Fix
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
          parameters: >
            [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

This change will use the default GitHub token that is automatically available in all GitHub Actions workflows, which should have the necessary permissions as defined in the `permissions` section of the job.
