### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#88]
## Root Cause Analysis

**Confidence Level:** 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub workflow is failing because it's trying to use the `PROJEN_GITHUB_TOKEN` secret which is not available or not properly configured in the repository. The error message "Parameter token or opts.auth is required" indicates that the GitHub API call is failing due to missing authentication.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Error Log
```
2025-06-23T23:49:20.7917929Z ##[error]Parameter token or opts.auth is required
```

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the standard `GITHUB_TOKEN` in the pr-triage-manager job
2. Update the workflow file to use the same token as the other successful jobs
3. Modify the code as follows:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

4. Commit the changes to the repository
5. Re-run the workflow to verify the fix
