### ISSUE TITLE
GitHub Workflow Failure: Missing PROJEN_GITHUB_TOKEN in pr-triage-manager job

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#90]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The `pr-triage-manager` job in the GitHub workflow is failing because it's trying to use a GitHub token named `PROJEN_GITHUB_TOKEN` that doesn't exist or isn't properly configured in the repository secrets.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

### Error Log
```
##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Update the workflow file to use the standard GITHUB_TOKEN instead of PROJEN_GITHUB_TOKEN
2. Replace the github-token parameter in the pr-triage-manager job with the standard token
3. Ensure the token has the necessary permissions for pull request operations
4. The corrected code should be:

```yaml
pr-triage-manager:
  permissions:
    issues: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: aws-github-ops/aws-issue-triage-manager@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "pull-requests"
        area-is-keyword: true
        default-area: >
          {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
        parameters: >
          [{"area":"pullrequests","keywords":["pullrequestkeyword"]}]
```

Note that the other jobs in the workflow (`issue-triage-manager` and `guidance-triage-manager`) are using the standard `GITHUB_TOKEN` and are working correctly. The `pr-triage-manager` job should follow the same pattern.
