### ISSUE TITLE
Authentication Failure in PR Triage Manager Workflow

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/aws-cdk-#99]
## Root Cause Analysis

**Confidence Level**: 95%

### Issue Summary
The GitHub Actions workflow "Set Issue Label and Assignee" is failing in the `pr-triage-manager` job due to an authentication issue. The job is attempting to use the `PROJEN_GITHUB_TOKEN` secret for authentication, but this token is either not defined in the repository secrets or is invalid.

### Impacted File
`.github/workflows/issue-label-assign.yml`

### Problematic Code
```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

### Error Message
```
2025-06-23T23:56:54.2345117Z ##[error]Parameter token or opts.auth is required
```

## Solution Plan

1. Replace the `PROJEN_GITHUB_TOKEN` with the default `GITHUB_TOKEN` that is automatically provided by GitHub Actions:

```yaml
pr-triage-manager:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: aws-github-ops/aws-issue-triage-manager@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: "pull-requests"
          area-is-keyword: true
          default-area: >
            {"reviewers":{"teamReviewers":["aws-cdk-owners"]}}
```

2. Alternatively, if `PROJEN_GITHUB_TOKEN` is required for specific permissions, ensure it's properly configured in the repository secrets.

3. Verify that the `aws-github-ops/aws-issue-triage-manager@main` action is correctly handling the token parameter.

4. If a custom token with specific permissions is needed, create a new secret with the required permissions and update the workflow to use it.
